package selectionCommitee.domain;

public enum FacultyName {
	EDUCATION, HUMANITIES, INFORMATION_TECHNOLOGY, FOREIGN_LANGUAGES, PHILOSOPHY, MATH, TOURISM, NATURAL_SCIENCES,
	PHYSIC, HISTORY, PEDAGOGY;
}
